---

- name: Install Virtualbox
  become: yes
  package:
    name: virtualbox
    state: latest
  when: vagrant_install_virtualbox

- name: Check Vagrant version
  shell: command -v vagrant 1>/dev/null 2>&1 && vagrant --version | sed 's/Vagrant //'
  register: check_version
  changed_when: no
  failed_when: no

- include: debian_install.yml
  when: "check_version.stdout != vagrant_version"
