---

- name: Create Vagrant installation temp directory
  file:
    path: "{{ vagrant_tmp }}"
    state: directory

- name: Set Vagrant package name
  set_fact:
    vagrant_package: vagrant_{{ vagrant_version }}_{{ vagrant_arch }}.deb

- name: Download Vagrant package
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/{{ vagrant_package }}"
    dest: "{{ vagrant_tmp }}/{{ vagrant_package }}"
    checksum: "{{ vagrant_checksum }}"

- name: Install Vagrant
  become: yes
  apt:
    deb: "{{ vagrant_tmp }}/{{ vagrant_package }}"

- name: Cleanup temp directory
  file:
    path: "{{ vagrant_tmp }}"
    state: absent
